In [1]:
import torch

X = torch.rand(7, 7)
X, X.shape

(tensor([[0.8582, 0.4163, 0.8059, 0.1968, 0.1276, 0.5707, 0.6424],
         [0.9073, 0.7256, 0.8208, 0.7539, 0.9291, 0.0490, 0.5678],
         [0.7983, 0.2504, 0.3707, 0.1348, 0.7632, 0.6214, 0.8386],
         [0.2678, 0.5535, 0.2251, 0.4323, 0.1435, 0.6661, 0.8805],
         [0.8022, 0.9836, 0.7537, 0.3682, 0.0386, 0.6036, 0.9372],
         [0.6113, 0.8610, 0.8797, 0.7289, 0.9664, 0.0533, 0.8094],
         [0.1957, 0.7726, 0.4013, 0.5863, 0.8418, 0.8915, 0.4419]]),
 torch.Size([7, 7]))

In [2]:
Y = torch.rand(1, 7)
Z = torch.matmul(X, Y.T)
Y, Z, Z.shape

(tensor([[0.8961, 0.9094, 0.8276, 0.2577, 0.9100, 0.6449, 0.1556]]),
 tensor([[2.4494],
         [3.3118],
         [2.5103],
         [1.7382],
         [2.9023],
         [3.2864],
         [2.7708]]),
 torch.Size([7, 1]))

In [4]:
torch.manual_seed(0)

X = torch.rand(7, 7)
Y = torch.rand(1, 7)
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [5]:
torch.manual_seed(1234)
X = torch.rand(2, 3)
Y = torch.rand(2, 3)
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]]),
 torch.Size([2, 2]))

In [6]:
Z.max(), Z.min()

(tensor(0.5617), tensor(0.3647))

In [7]:
torch.manual_seed(7)
X = torch.rand(1, 1, 1, 10)
Y = torch.squeeze(X)
X, X.shape, Y, Y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))